site_name: OSG Virtual School Pilot 2020
site_url: https://opensciencegrid.org/virtual-school-pilot-2020/
repo_name: null
repo_url: null
theme:
  name: windmill
  custom_dir: theme-customizations

extra:
  article_nav_top: false

extra_css:
  - css/extra.css
  - css/codehilite.css

# Suppress weird JavaScript problems with development server
extra_javascript: []

pages:
  - Virtual School Pilot 2020:    index.md
  - Schedule:                     schedule.md
  - Materials:
    - Overview:                   materials/index.md
    - HTC Exercises:
      - Exercise 1.1:             materials/htc/part1-ex1-login.md
    - OSG Exercises:
      - Placeholder:              materials/osg/temp.md
    - Software Exercises:
      - Exercise 1 (Required): materials/sw/ex1-required-download.md
      - Exercise 2 (Required): materials/sw/ex2-required-wrapper.md
      - Exercise 3a (Pick one of 3a-3d): materials/sw/ex3a-compiling.md
      - Exercise 3b (Pick one of 3a-3d): materials/sw/ex3b-prepackaged.md
      - Exercise 3c (Pick one of 3a-3d): materials/sw/ex3c-python-built.md
      - Exercise 3d (Pick one of 3a-3d): materials/sw/ex3d-matlab.md
      - Exercise 4 (Required): materials/sw/ex4-singularity.md
      - Exercise 5a (optional): materials/sw/ex5a-arguments.md
      - Exercise 5b (optional): materials/sw/ex5b-python-extras.md
      - Exercise 5c (optional): materials/sw/ex5c-docker.md
    - Data Exercises:
      - Placeholder:              materials/data/temp.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - osg_markdown.colors
